#!/usr/bin/env bash
#Web servers are the piece of software generating and serving HTML pages

sudo apt -y update
sudo apt install nginx
sudo service nginx restart
echo "Hello world" | sudo tee /usr/share/nginx/html/index.html
